### ISSUE TITLE
Issues on my compiling environment

### ISSUE THREAD

**Issue by jianqiucao** [GJDuck/LowFat#1]
Hi Dr. Duck,

I encountered two issues while building the LowFat project. They are just due to my environment setup rather than your code.

I'm running it in Ubuntu 16.04 in VMWare. The host OS is Windows 10.

1. Firstly I tried to build the project by running the "build.sh" in a shared folder with windows and the "ln -fs" command was denied NTFS file system doesn't support symbolic link.

2. Then I copied the project folder into a Linux directory and built it. As I haven't installed cmake, the script quitted after the prompt "./build.sh: will now build LLVM..." with an error message. 

Then I installed cmake and rebuilt the project. However, the the script quitted after the prompt "./build.sh: will now build LLVM..." with the error message "make: *** No targets specified and no makefile found.  Stop."

I think the problem was due to the previous build was partially finished, and the folder "bootstrap" was created, but the files were incompletely copied there.

So I deleted the "bootstrap" folder and rebuilt it again. Then it worked.

I know the issues are due to my environment setup, however, could you add some notices in the readme file, or add more checks in the "build.sh" script for other users to avoid similar errors?

Thanks,
Jianqiu Cao

**Comment by GJDuck** [comment]
Thanks for the report.  The build process for LowFat is a bit of a mess, so the `build.sh` script is meant to hide all that.  I'll try to fix cmake problem at least.
