### ISSUE TITLE
Improving lowfat_stack_mirror

### ISSUE THREAD

**Issue by janhoogerbrugge** [GJDuck/LowFat#13]
This is the original code to implement lowfat_stack_mirror:

        Value *Offsets = M->getOrInsertGlobal("lowfat_stack_offsets",
            ArrayType::get(builder.getInt64Ty(), 0));
        if (GlobalVariable *Global = dyn_cast<GlobalVariable>(Offsets))
            Global->setConstant(true);

Replacing this by:

        int size = sizeof(lowfat_stack_offsets) / sizeof(lowfat_stack_offsets[0]);
        ArrayType *type = ArrayType::get(builder.getInt64Ty(), size);
        Value *Offsets = M->getOrInsertGlobal("lowfat_stack_offsets", type);
        if (GlobalVariable *Global = dyn_cast<GlobalVariable>(Offsets))
        {
            vector<Constant *> values(size);
            for (int i = 0; i < size; i++)
                values[i] = builder.getInt64(lowfat_stack_offsets[i]);
            Global->setConstant(true);
            Global->setInitializer(ConstantArray::get(type, values));
            Global->setLinkage(GlobalValue::InternalLinkage);
        }

makes that a successive optimization pass replaces the table lookup by the proper 
entry from lowfat_stack_offsets if the index is constant (which is most of the time).

It works. However running 433.milc with protecting only the writes makes that the 
benchmarks crashes (at run-time). All other benchmarks of SPEC2006 run fine.
I narrowed it down to the pp array in make_loop_table and add_basic_path. Any 
idea what might be wrong. The optimization seems so trivial.

Doing the replacement of a table lookup by the entry in the lowfat pass itself instead
of a later pass is not working as well. It fails in the same way.

**Comment by GJDuck** [comment]
IIRC the `lowfat_stack_offsets` global is deliberately not inlined, since it generates more compact code.  The offsets are large values, so they must be read from memory one way or the other.  By inlining the compiler will usually emit a fat `movabs` instruction to load the constant offset into a register.  In this case, it may better not to inline and use base+offset addressing from a single global location, e.g.:

    add lowfat_stack_offsets+464(%rip), %rbx

However, there *is* still a potential performance bug.  In time between the NDSS paper and the release we added global variable support, which requires the "large" code model.  This meant the compiler uses a `movabs` regardless, in which case the constant offset may as well be inlined.  I may look into this.

I am not sure why `milc` crashes off the top of my head, I'd have to look into it.

For the non-crashing benchmarks, was there any performance gain?

**Comment by janhoogerbrugge** [comment]
I target AArch64. With the large code model it takes 4 instructions to create the lowfat_stack_offsets label which is then followed by a load. Using the entry directly takes only one or two instructions because AArch64 can load 64b immediates efficiently when these values have many bits zero in them.

This simple piece of code:

    void foo() 
    {
      int a[3];
      bar(a); 
    }

Takes 13 AArch64 instructions (each 32b) without the modification and 11 instructions (again all 32b) with the modification. (The code takes 8 instructions without low fat pointer protection).

On SPEC2006 is see an average performance improvement of 1.3%. Again, this is on AArch64.

Another modification that might make sense is to add the following to isInterestingAlloca():

    if (!isa<ArrayType>(Alloca->getAllocatedType()) && isa<ConstantInt>(Alloca->getArraySize()))
        return false;

This prevents stack mirroring on scalar local variables. Consider this code for example:

    void foo()
    {
      struct S s;
      bar(&s);
      ...
    }

When this is programmed it is unlikely that bar(struct s *p) will access p[...]. If s would be an array or a VLA then this would be more likely. Do you agree? I agree that I give up a bit of protection for less overhead.

**Comment by GJDuck** [comment]
A 1.3% speedup is a nice result, so definitely worth including.  I am not familiar with the AArch64 but would probably affect some design decisions.

I've also created a branch where `lowfat_stack_offsets` is forced to be a 32bit pointer value.  I have not tested it yet, but may also yield a modest gain (not very many benchmarks are bound by stack allocation speed though).

Also, we would welcome a AArch64 port if you choose to make it available.

> Another modification that might make sense is to add the following to isInterestingAlloca():

This could be added as an option that trades instrumentation for performance.

**Comment by GJDuck** [comment]
I have inlined the constant in master.  I have not tested the performance but at least it simplifies the code.  I did not notice any crash with `milc`.
