### ISSUE TITLE
SPEC-CPU2006 crashes

### ISSUE THREAD

**Issue by taddeus** [GJDuck/LowFat#17]
I am trying to reproduce the performance results on SPEC-CPU2006 but 5 benchmarks (perlbench, gcc, milc, namd, soplex) crash on the test workload when compiled with LowFat. This is likely because a blacklist file is needed to disable instrumentation in some functions. Could you provide this file perhaps?

**Comment by GJDuck** [comment]
Hi, the following might work.  Not sure if it is up-to-date or not.

    # perlbench
    fun:S_regbranch
    fun:S_nextchar
    fun:S_regatom
    fun:S_regmatch
    
    # gcc
    fun:init_alias_analysis
    fun:cse_basic_block
    fun:cse_insn
    fun:insert_regs
    fun:insert
    fun:canon_reg
    fun:delete_reg_equiv
    fun:cse_process_notes
    fun:fold_rtx
    fun:canon_rtx
    fun:cse_rtx_varies_p
    fun:equiv_constant
    fun:record_jump_cond
    fun:reload
    fun:set_label_offsets
    fun:set_offsets_for_label
    fun:end_alias_analysis
    fun:invalidate
    fun:invalidate_for_call
    fun:merge_equiv_classes
    fun:mark_constant_function
    
    # h264ref
    fun:biari_init_context
    fun:init_contexts
    
    # namd
    fun:_ZN11ObjectArenaIcE11getNewArrayEi
    
    # soplex
    fun:_ZN6soplex5SVSet5reMaxEi
    fun:_ZN6soplex5SVSet8memRemaxEi
    fun:_ZN6soplex5SVSet6createEi
    fun:_ZN6soplex5SVSet5xtendERNS_7SVectorEi

**Comment by taddeus** [comment]
Thanks for the list. It is indeed not entirely complete: I had to add fun:Perl_pp_split for perlbench and fun:load_longlinks for milc to get rid of OOB errors. Still, milc produces an error: there is a miscompare in its output when instrumented with LowFat. Did you maybe use a source patch for this during evaluation?

On a side note: the blacklist for perlbench seems a bit extreme since S_regmatch is a massive function that is used a lot on the hot path. Entirely disabling instrumentation for it likely reduces runtime overhead by a lot compared to only blacklisting a specific problem case.

**Comment by GJDuck** [comment]
I've re-run `milc` but did not have any issue.  What compiler flags are you using?  Normally we use

    -fsanitize=lowfat -mllvm -lowfat-no-check-blacklist=blacklist.txt -O2

There should not be any miscompares so perhaps there is a bug somewhere.

Normally, the exact blacklist depends on the optimization level, which is why I was reluctant to release an "official" blacklist.  This is because function inlining can "resolve" OOB-escapes.

As for perlbench, I am not sure we looked too deeply into it.  Certainly it is preferable to blacklist specific locations if possible.  Even better is to patch the program itself, but it is not easy to diagnose and make changes to the perl implementation.

**Comment by taddeus** [comment]
Hmm, strange. I'm using exactly those flags as well. Inlining decisions should be deterministic so with the same compiler version and flags, the same blacklist should work across machines in principle I would say.

The only thing I can think of that would cause a miscompare is is a pointer subtraction between an uninstrumented and an instrumented pointer. Maybe the now blacklisted function contained some malloc call was replaced with a lowfat malloc but not anymore.

**Comment by GJDuck** [comment]
Yes it is strange.  The fact that you need a different blacklist indicates some inconsistency.  Maybe I have time to look at it more closely next week.
