### ISSUE TITLE
Build low fat failing in ubuntu 20.4

### ISSUE THREAD

**Issue by tareq97-zz** [GJDuck/LowFat#20]
Hi,

I facing issues to build the lowfat project using the build.sh file. Please find the issues mentioned in the screenshot below

![pic1](https://user-images.githubusercontent.com/10094302/120174970-fc647880-c205-11eb-94a7-e525e38be0f6.png)

**Comment by GJDuck** [comment]
Someone has already made a pull request that should fix this and other issues, see #19.

Actually, I really ought to merge it, but never got around to testing it.  So I would appreciate any feedback if you try it out.

**Comment by tareq97-zz** [comment]
Hi @GJDuck,

Thanks for the reply,

Ok so the pull request is not merged. I will try and use the changes done in the pull request #19 and try it.

**Comment by tareq97-zz** [comment]
Hi,

Actually I am trying to compile a c file using the clang in lowfat project with fsanitize=lowfat option. But I am getting below mentioned error. It is able to create a s.c.in.lowfat.ll and s.c.out.lowfat.ll file but not the object file for the s.c program.  Please let me know if this the issues with lowfat.
![linker-error](https://user-images.githubusercontent.com/10094302/120472285-fc9b7a00-c3a5-11eb-8e2f-320a929b1196.png)

**Comment by GJDuck** [comment]
I am not sure what causes that problem.  When I try my installed version, it works without that error.

Perhaps you can check if the `build/lib/LowFat/lowfat.ld` file exists in your build directory.  If not, maybe it is possible to manually copy it from the `config/` directory.

**Comment by tareq97-zz** [comment]
@GJDuck thanks for the reply. copying the file works. 

But also I ran into one more error related to LLVM. Please find the error, for the first commands that are executed. It not able to recognize the -lowfat-symbolize command. Without this command it is generating the output.

![error](https://user-images.githubusercontent.com/10094302/120724581-69149700-c4d4-11eb-920b-ac0bc945f856.png)

**Comment by GJDuck** [comment]
There is no `-lowfat-symbolize` option in the LowFat implementation.

I think you mean like the ASAN symbolize option?  Something like this was never implemented for LowFat unfortunately.

**Comment by tareq97-zz** [comment]
Hi @GJDuck ,

Thanks for the input. But actually I was trying to replicate the experiments mentioned in the paper https://extractfix.github.io/. The experiments work fine in docker image mentioned in this demo document https://extractfix.github.io/demo.pdf. But while running the same experiment on the system I just rushed into some issues. For running the demo few cflags are used cflags="$cflags -fsanitize=lowfat -mllvm -lowfat-debug -mllvm -lowfat-no-check-memset -mllvm -lowfat-no-check-memcpy -mllvm -lowfat-no-check-escapes -mllvm -lowfat-no-check-fields -mllvm -lowfat-symbolize -lstlimpl". Just wanted to clarify whether the version of lowfat used for this literature is same as the one mentioned in the github. Because as per the literature to generate the **"cfc.out"** file we need to provide the -lowfat-symbolize option.

**Comment by GJDuck** [comment]
> Just wanted to clarify whether the version of lowfat used for this literature is same as the one mentioned in the github.

Indeed ExtractFix does use a modified version and it is available here: https://github.com/wangbo15/LowFat
