### ISSUE TITLE
README memory region #1 #2 accidentally point to Issues

### ISSUE THREAD

**Issue by FeynmanDNA** [GJDuck/LowFat#23]
![image](https://user-images.githubusercontent.com/26617036/160239153-94fbebe5-0108-4af2-b5e7-3f467f76aee4.png)

The text in the README uses "#" followed by 1 and 2, but Github parses it as Github issues:
```
For example, region #1 is used for allocations of size 1-16bytes, region #2
for allocations of size 17-32bytes, etc.  Furthermore, all LowFat allocated
objects are aligned to allocation-size boundaries.
```

Maybe can enclose the `#1` and `#2` text in back-ticks to escape the parsing

**Comment by GJDuck** [comment]
Thanks.
