### ISSUE TITLE
Code is not protected

### ISSUE THREAD

**Issue by janhoogerbrugge** [GJDuck/LowFat#8]
Hi,

This code is not protected (when compiled with -fsanitize=lowfat):

void copy(char *dst, const char *src)
{
  while(*src)
    *dst++ = *src++;
  *dst++ = '\0';
}

This is the produced IR:

define void @copy(i8*, i8*) #0 {
  br label %3

; <label>:3:                                      ; preds = %8, %2
  %4 = phi i8* [ %1, %2 ], [ %9, %8 ]
  %5 = phi i8* [ %0, %2 ], [ %11, %8 ]
  %6 = load i8, i8* %4, align 1
  %7 = icmp ne i8 %6, 0
  br i1 %7, label %8, label %12

; <label>:8:                                      ; preds = %3
  %9 = getelementptr inbounds i8, i8* %4, i32 1
  %10 = load i8, i8* %4, align 1
  %11 = getelementptr inbounds i8, i8* %5, i32 1
  store i8 %10, i8* %5, align 1
  br label %3

; <label>:12:                                     ; preds = %3
  %13 = getelementptr inbounds i8, i8* %5, i32 1
  store i8 0, i8* %5, align 1
  ret void
}

When I rewrite it to the following code, it gets correctly protected:

void copy2(char *dst, const char *src)
{
  int i;
  for(i = 0; src[i]; i++)
    dst[i] = src[i];
  dst[i] = '\0';
}

It would be nice to automatically replace string functions like strcpy in the same way as 
memory functions are replaced. For example:

char *lowfat_strcpy(char *dst, const char *src)
{
  int srclen = strlen(src);

  lowfat_oob_check(LOWFAT_OOB_ERROR_STRCPY, src, srclen + 1, src);
  lowfat_oob_check(LOWFAT_OOB_ERROR_STRCPY, dst, srclen + 1, dst);

  return strcpy(dst, src);
}

Regards,
Jan.

**Comment by janhoogerbrugge** [comment]
It would also be nice to have a replacement for the famous gets function. Otherwise
when libc is not compiled with -fsanitize=lowfat gets can still cause damage.

**Comment by GJDuck** [comment]
Thanks for the report.  There was a bug in one of the internal analysis which affects the `no-check-whole-access` mode.  I've committed a quick fix, but that code has been rewritten a few times, so may need to revisit it again when I have the time.

As for lowfat-ized stdlibc functions, this was always an idea but never got around to implementing it.  Tools like `AddressSanitizer` intercept many functions and there is no reason why LowFat can not do the same.
